name: adoptly01
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  dotted_border: ^2.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_adoptly.png
    - assets/images/perrito_presentacion.png
    - assets/images/perrito_gatito_inicio.png
    - assets/images/max.png
    - assets/images/luna.png
    - assets/images/rocky.png
    - assets/images/milo.png
    - assets/images/bella.png
    - assets/images/nube.png
